language: clojure

jdk:
  - openjdk8
  - oraclejdk8

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -yq nodejs curl
  - cd manager-interface && npm install && npm run build && cd -

script: lein test
