language: clojure

jdk:
  - openjdk8
  - oraclejdk8

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -yq nodejs curl
  - cd manager-interface && npm install && npm run build && cd -

script: lein test

after_success:
- CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json