restql:
  image: restql-server:alpine
  restart: always
  environment:
    - mongo-url=mongodb://mongodb:27017/restql
    - planets=http://swapi.co/api/planets/
  links:
    - mongodb
  ports:
    - "0.0.0.0:9000:9000"

mongodb:
  image: mongo:3.4

nginx:
  image: nginx:1.12-alpine
  volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  links:
    - restql
  ports:
    - 8080:80
